// <auto-generated />
using System;
using Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630041941_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client.Model.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_DonViTinh")
                        .IsUnique();

                    b.ToTable("DonViTinhs");
                });

            modelBuilder.Entity("Client.Model.HieuChinhThongTinPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int?>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kho_ID");

                    b.HasIndex("NCC_ID");

                    b.ToTable("HieuChinhThongTinPhieuNhaps");
                });

            modelBuilder.Entity("Client.Model.Kho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Kho")
                        .IsUnique();

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("Client.Model.KhoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_Dang_Nhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_Dang_Nhap", "Kho_ID")
                        .IsUnique();

                    b.ToTable("KhoUsers");
                });

            modelBuilder.Entity("Client.Model.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_LSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_LSP")
                        .IsUnique();

                    b.HasIndex("Ten_LSP")
                        .IsUnique();

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("Client.Model.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma_NCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_NCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_NCC")
                        .IsUnique();

                    b.ToTable("NhaCungCaps");
                });

            modelBuilder.Entity("Client.Model.NhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhoId")
                        .HasColumnType("int");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("int");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_Kho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten_NCC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique();

                    b.ToTable("NhapKhos");
                });

            modelBuilder.Entity("Client.Model.NhapKhoRawData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Nhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nhap_Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nhap_Kho_ID");

                    b.HasIndex("San_Pham_ID");

                    b.ToTable("NhapKhoRawDatas");
                });

            modelBuilder.Entity("Client.Model.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonViTinhId")
                        .HasColumnType("int");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiSanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("Ma_SP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten_SP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViTinhId");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("Ma_SP")
                        .IsUnique();

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Client.Model.XuatKhoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Don_Gia_Xuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SL_Xuat")
                        .HasColumnType("int");

                    b.Property<string>("San_Pham_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xuat_Kho_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Xuat_Kho_ID");

                    b.ToTable("XuatKhoRaw");
                });

            modelBuilder.Entity("Client.Model.XuatKhoEdit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ghi_Chu");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int")
                        .HasColumnName("Kho_ID");

                    b.Property<DateTime>("Ngay_Xuat_Kho")
                        .HasColumnType("datetime2")
                        .HasColumnName("Ngay_Xuat_Kho");

                    b.Property<string>("So_Phieu_Xuat_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("So_Phieu_Xuat_Kho");

                    b.HasKey("Id");

                    b.ToTable("tbl_XNK_Xuat_Kho");
                });

            modelBuilder.Entity("Client.Model.XuatKhoHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Xuat_Kho")
                        .HasColumnType("datetime2");

                    b.Property<string>("So_Phieu_Xuat_Kho")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("So_Phieu_Xuat_Kho")
                        .IsUnique();

                    b.ToTable("XuatKho");
                });

            modelBuilder.Entity("Client.Model.HieuChinhThongTinPhieuNhap", b =>
                {
                    b.HasOne("Client.Model.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Kho_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Client.Model.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NCC_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("Client.Model.NhapKho", b =>
                {
                    b.HasOne("Client.Model.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoId");

                    b.HasOne("Client.Model.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId");

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("Client.Model.NhapKhoRawData", b =>
                {
                    b.HasOne("Client.Model.NhapKho", "NhapKho")
                        .WithMany("NhapKhoRawDatas")
                        .HasForeignKey("Nhap_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client.Model.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("San_Pham_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhapKho");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Client.Model.SanPham", b =>
                {
                    b.HasOne("Client.Model.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("DonViTinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Client.Model.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("Client.Model.XuatKhoDetail", b =>
                {
                    b.HasOne("Client.Model.XuatKhoHeader", "PhieuXuat")
                        .WithMany("ChiTiet")
                        .HasForeignKey("Xuat_Kho_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("Client.Model.NhapKho", b =>
                {
                    b.Navigation("NhapKhoRawDatas");
                });

            modelBuilder.Entity("Client.Model.XuatKhoHeader", b =>
                {
                    b.Navigation("ChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
